name: Integration Tests
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  integration-test-release_21_0_x-release_2_0_x:
    name: Integration Test - eosjs release/21.0.x with nodeos release/2.0.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/21.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.0.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-release_21_0_x-release_2_1_x:
    name: Integration Test - eosjs release/21.0.x with nodeos release/2.1.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/21.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.1.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-release_21_0_x-develop:
    name: Integration Test - eosjs release/21.0.x with nodeos develop
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/21.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:develop

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-release_22_0_x-release_2_0_x:
    name: Integration Test - eosjs release/22.0.x with nodeos release/2.0.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
        env:
          NODEOS_VER: 'release/2.0.x'
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
        env:
          CYPRESS_NODEOS_VER: 'release/2.0.x'
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.0.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-release_22_0_x-release_2_1_x:
    name: Integration Test - eosjs release/22.0.x with nodeos release/2.1.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.1.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-release_22_0_x-develop:
    name: Integration Test - eosjs release/22.0.x with nodeos develop
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:develop

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-develop-release_2_0_x:
    name: Integration Test - eosjs develop with nodeos release/2.0.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: develop
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
        env:
          NODEOS_VER: 'release/2.0.x'
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
        env:
          CYPRESS_NODEOS_VER: 'release/2.0.x'
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.0.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-develop-release_2_1_x:
    name: Integration Test - eosjs develop with nodeos release/2.1.x
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: develop
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
        env:
          NODEOS_VER: 'release/2.1.x'
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
        env:
          CYPRESS_NODEOS_VER: 'release/2.1.x'
    services:
      nodeos:
        image: eosio/eosjs-ci:release_2.1.x

        ports:
          - 8888:8888
          - 9876:9876
  integration-test-develop-develop:
    name: Integration Test - eosjs develop with nodeos develop
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: develop
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:develop

        ports:
          - 8888:8888
          - 9876:9876
